/**
 * INVESTOR & FUNDER MAPPING AGENT
 * --------------------------------
 * Maps Belfast-based and NI-focused private investors, philanthropists,
 * and corporate funders relevant to the Fernhill Heritage Vision.
 *
 * Outputs:
 *   research-output/investors/investors.json
 *   research-output/investors/investors.md
 *
 * Data targets:
 *   - High-net-worth individuals with NI heritage/community interest
 *   - Local business owners with philanthropy track records
 *   - Social impact investors active in NI
 *   - Corporate sponsors with Belfast CSR programmes
 *   - Investment return expectations and engagement models
 */

import fs from "fs/promises";
import path from "path";

const OUTPUT_DIR = "research-output/investors";

const RESEARCH_SCOPE = {
  topic: "Private Investor & Philanthropic Funder Mapping — Belfast/NI",
  geographicFocus: "Belfast, Northern Ireland",
  dataPoints: [
    "Named individuals with known NI heritage/community philanthropy",
    "Belfast business families with charitable giving history",
    "Social impact investors with NI portfolio",
    "Corporate sponsors active in Belfast cultural/heritage sector",
    "Investment models: loan, equity, social bond, community shares, grant/gift",
    "Typical return expectations by investor type",
    "Engagement and stewardship approach",
  ],
};

const placeholderData = {
  meta: {
    agent: "investor-agent",
    version: "1.0.0",
    generated: new Date().toISOString(),
    status: "scaffold — populate via AI research run",
  },
  investorCategories: [
    {
      category: "Heritage-Aligned Philanthropists",
      description: "Individuals who have previously supported NI heritage or cultural causes",
      engagementModel: "Gift or grant (non-repayable). Named gift opportunities.",
      examples: [
        {
          name: "TODO: Named NI philanthropist",
          knownInterests: "TODO",
          previousGiving: "TODO",
          source: "TODO",
        },
      ],
    },
    {
      category: "Social Impact Investors",
      description: "Funds and individuals seeking social return alongside financial return",
      engagementModel: "Repayable loan at below-market rate (1–4%); patient capital 10–15 yr",
      examples: [
        {
          name: "Social Investment Scotland / Ulster Community Investment Trust",
          knownInterests: "Community asset ownership, social enterprise",
          previousGiving: "TODO",
          source: "TODO",
        },
        {
          name: "Charity Bank",
          knownInterests: "Loans to charities and social enterprises",
          previousGiving: "TODO",
          source: "https://www.charitybank.org",
        },
      ],
    },
    {
      category: "Corporate Sponsors",
      description: "Belfast businesses with active CSR programmes",
      engagementModel: "Sponsorship packages with naming rights, event access, PR value",
      examples: [
        {
          name: "TODO: Belfast law firms, property developers, financial services",
          knownInterests: "TODO",
          previousGiving: "TODO",
          source: "TODO",
        },
      ],
    },
    {
      category: "Diaspora Donors",
      description: "Irish/Belfast diaspora in USA, Canada, Australia with heritage giving interest",
      engagementModel: "Gift (US donors can use American Ireland Fund for tax efficiency)",
      examples: [
        {
          name: "The American Ireland Fund",
          knownInterests: "Peace, reconciliation, culture, heritage",
          previousGiving: "TODO",
          source: "https://www.irelandfunds.org",
        },
      ],
    },
  ],
  engagementStrategy: {
    tier1: "Lead gifts (£100k+) — personal cultivation by Chair/CEO",
    tier2: "Major gifts (£10k–£100k) — named opportunity proposition",
    tier3: "Community giving (£100–£10k) — community shares / crowdfund",
    digitalFundraising: "Crowdfunding platform (e.g. Spacehive, Patronicity) for community phase",
  },
  citations: [],
};

async function run() {
  console.log("[investor-agent] Starting research run...");

  const jsonOutput = JSON.stringify(placeholderData, null, 2);
  const mdOutput = `# Investor & Philanthropic Funder Mapping — Research Report
*Generated by investor-agent v1.0.0 | ${new Date().toISOString()}*
*Status: scaffold — live data not yet populated*

---

## Investor Categories

${placeholderData.investorCategories
  .map(
    (c) => `### ${c.category}
- **Description:** ${c.description}
- **Engagement model:** ${c.engagementModel}

**Examples:**
${c.examples
  .map(
    (e) => `- **${e.name}**
  - Interests: ${e.knownInterests}
  - Previous giving: ${e.previousGiving}
  - Source: ${e.source}`
  )
  .join("\n")}
`
  )
  .join("\n")}

---

## Engagement Strategy

| Tier | Threshold | Approach |
|------|-----------|----------|
| Tier 1 | £100k+ | ${placeholderData.engagementStrategy.tier1} |
| Tier 2 | £10k–£100k | ${placeholderData.engagementStrategy.tier2} |
| Tier 3 | £100–£10k | ${placeholderData.engagementStrategy.tier3} |
| Digital | Any | ${placeholderData.engagementStrategy.digitalFundraising} |

---

## Citations

*TODO: Add numbered citations with URLs.*

---
*This report is a scaffold. Run the agent with live AI research enabled to populate all TODO fields.*
`;

  await fs.mkdir(OUTPUT_DIR, { recursive: true });
  await fs.writeFile(path.join(OUTPUT_DIR, "investors.json"), jsonOutput, "utf8");
  await fs.writeFile(path.join(OUTPUT_DIR, "investors.md"), mdOutput, "utf8");

  console.log("[investor-agent] Outputs written to", OUTPUT_DIR);
  return placeholderData;
}

export { run, RESEARCH_SCOPE };
