/**
 * OPERATIONS MODELLING AGENT
 * ---------------------------
 * Models operational structures, capacity, staffing, and revenue
 * for the proposed Fernhill Heritage venue.
 *
 * Outputs:
 *   research-output/operations/operations.json
 *   research-output/operations/operations.md
 *
 * Data targets:
 *   - Staffing models for each revenue stream
 *   - Capacity estimates per use (weddings, wakes, tea room, cinema, events)
 *   - Revenue modelling — price × volume × margin
 *   - Cost structures (fixed vs variable)
 *   - Break-even analysis
 *   - Year 1–5 revenue projections
 */

import fs from "fs/promises";
import path from "path";

const OUTPUT_DIR = "research-output/operations";

const RESEARCH_SCOPE = {
  topic: "Operational Models & Revenue Modelling — Fernhill Heritage Venue",
  geographicFocus: "Fernhill House, Belfast",
  dataPoints: [
    "Staffing requirements by revenue stream (FTE and casual)",
    "Capacity per event type",
    "Pricing assumptions (based on market research)",
    "Annual volume assumptions (events per year)",
    "Revenue per stream",
    "Direct costs per stream",
    "Contribution margin per stream",
    "Fixed overhead estimate",
    "Break-even event volume",
    "Year 1–5 revenue model",
  ],
};

const placeholderData = {
  meta: {
    agent: "operations-agent",
    version: "1.0.0",
    generated: new Date().toISOString(),
    status: "scaffold — populate via AI research run",
  },
  capacityAssumptions: {
    weddingCeremony: "TODO: 60–120 guests (main hall + garden)",
    weddingReception: "TODO: 80–150 guests (dining + dancing)",
    wakeReception: "TODO: 40–100 guests (standing/seated mix)",
    teaRoom: "TODO: 30–50 covers (daily, lunch service)",
    cinemaRoom: "TODO: 30–40 seats",
    communityEvents: "TODO: 50–200 depending on configuration",
  },
  revenueStreams: [
    {
      stream: "Weddings",
      pricePerEvent: "TODO: £3,500–£8,000 venue hire",
      annualEvents: "TODO: 30–50 weddings/year at maturity",
      annualRevenue: "TODO",
      directCostRatio: "TODO: ~30–40%",
      contributionMargin: "TODO",
      notes: "Primary revenue driver. Weekends only initially.",
    },
    {
      stream: "Wakes & Funeral Receptions",
      pricePerEvent: "TODO: £600–£1,500 venue hire + catering",
      annualEvents: "TODO: 60–100 per year",
      annualRevenue: "TODO",
      directCostRatio: "TODO: ~40–50%",
      contributionMargin: "TODO",
      notes: "Weekday revenue anchor. High community value.",
    },
    {
      stream: "Tea Room",
      pricePerCover: "TODO: £12–£18 average spend",
      annualCovers: "TODO",
      annualRevenue: "TODO",
      directCostRatio: "TODO: ~55–65% (F&B margins)",
      contributionMargin: "TODO",
      notes: "Daily community activation. Lower margin, high footfall value.",
    },
    {
      stream: "Heritage Cinema",
      pricePerTicket: "TODO: £8–£12",
      annualScreenings: "TODO: 2–3/week",
      annualRevenue: "TODO",
      directCostRatio: "TODO: ~30–40%",
      contributionMargin: "TODO",
      notes: "Community programming. Licensing required.",
    },
    {
      stream: "Community Events & Room Hire",
      pricePerEvent: "TODO: £150–£500/day",
      annualEvents: "TODO",
      annualRevenue: "TODO",
      directCostRatio: "TODO: ~20–30%",
      contributionMargin: "TODO",
      notes: "Fills capacity gaps. Builds community relationships.",
    },
  ],
  staffingModel: {
    coreTeam: [
      { role: "Venue Manager", fte: 1, annualCost: "TODO: ~£35–45k" },
      { role: "Events Coordinator", fte: 1, annualCost: "TODO: ~£28–35k" },
      { role: "Tea Room Manager", fte: 1, annualCost: "TODO: ~£25–30k" },
      { role: "Maintenance/Grounds", fte: 1, annualCost: "TODO: ~£22–28k" },
    ],
    casualStaff: "TODO: 4–8 casual events staff at NLW+",
    totalStaffingCost: "TODO: ~£150–200k/yr at maturity",
  },
  financialModel: {
    year1Revenue: "TODO: ~£150–200k (ramp-up year)",
    year3Revenue: "TODO: ~£350–450k (approaching maturity)",
    year5Revenue: "TODO: ~£450–600k (full maturity)",
    fixedOverheads: "TODO: ~£200–250k/yr (staff + utilities + maintenance + insurance)",
    breakEvenRevenue: "TODO",
    breakEvenWeddings: "TODO: estimate weddings needed to cover fixed costs",
  },
  citations: [],
};

async function run() {
  console.log("[operations-agent] Starting research run...");

  const jsonOutput = JSON.stringify(placeholderData, null, 2);
  const mdOutput = `# Operational Models & Revenue Modelling — Research Report
*Generated by operations-agent v1.0.0 | ${new Date().toISOString()}*
*Status: scaffold — live data not yet populated*

---

## Capacity Assumptions

| Use | Proposed Capacity |
|-----|-------------------|
| Wedding Ceremony | ${placeholderData.capacityAssumptions.weddingCeremony} |
| Wedding Reception | ${placeholderData.capacityAssumptions.weddingReception} |
| Wake Reception | ${placeholderData.capacityAssumptions.wakeReception} |
| Tea Room | ${placeholderData.capacityAssumptions.teaRoom} |
| Cinema Room | ${placeholderData.capacityAssumptions.cinemaRoom} |
| Community Events | ${placeholderData.capacityAssumptions.communityEvents} |

---

## Revenue Streams

${placeholderData.revenueStreams
  .map(
    (r) => `### ${r.stream}
- **Price per event/cover/ticket:** ${r.pricePerEvent || r.pricePerCover || r.pricePerTicket}
- **Annual volume:** ${r.annualEvents || r.annualCovers || r.annualScreenings}
- **Annual revenue:** ${r.annualRevenue}
- **Direct cost ratio:** ${r.directCostRatio}
- **Contribution margin:** ${r.contributionMargin}
- **Notes:** ${r.notes}
`
  )
  .join("\n")}

---

## Staffing Model

### Core Team

| Role | FTE | Annual Cost |
|------|-----|-------------|
${placeholderData.staffingModel.coreTeam
  .map((s) => `| ${s.role} | ${s.fte} | ${s.annualCost} |`)
  .join("\n")}

**Casual staff:** ${placeholderData.staffingModel.casualStaff}
**Total staffing cost:** ${placeholderData.staffingModel.totalStaffingCost}

---

## Financial Model Summary

| Metric | Value |
|--------|-------|
| Year 1 Revenue | ${placeholderData.financialModel.year1Revenue} |
| Year 3 Revenue | ${placeholderData.financialModel.year3Revenue} |
| Year 5 Revenue | ${placeholderData.financialModel.year5Revenue} |
| Fixed Overheads | ${placeholderData.financialModel.fixedOverheads} |
| Break-even Revenue | ${placeholderData.financialModel.breakEvenRevenue} |
| Break-even Weddings | ${placeholderData.financialModel.breakEvenWeddings} |

---

## Citations

*TODO: Add numbered citations with URLs.*

---
*This report is a scaffold. Run the agent with live AI research enabled to populate all TODO fields.*
`;

  await fs.mkdir(OUTPUT_DIR, { recursive: true });
  await fs.writeFile(path.join(OUTPUT_DIR, "operations.json"), jsonOutput, "utf8");
  await fs.writeFile(path.join(OUTPUT_DIR, "operations.md"), mdOutput, "utf8");

  console.log("[operations-agent] Outputs written to", OUTPUT_DIR);
  return placeholderData;
}

export { run, RESEARCH_SCOPE };
