/**
 * RESTORATION COST RESEARCH AGENT
 * ---------------------------------
 * Researches heritage building restoration cost benchmarks in NI.
 *
 * Outputs:
 *   research-output/restoration/restoration.json
 *   research-output/restoration/restoration.md
 *
 * Data targets:
 *   - Cost per m² for listed building restoration in NI
 *   - Elemental costs: roof, windows, masonry, plaster, timber, services
 *   - Case studies from NI heritage restoration projects
 *   - Typical project timelines and phasing
 *   - Risk factors and contingency norms
 *   - Planning and listed building consent process (Historic Environment Division)
 */

import fs from "fs/promises";
import path from "path";

const OUTPUT_DIR = "research-output/restoration";

const RESEARCH_SCOPE = {
  topic: "Heritage Building Restoration Costs — Northern Ireland",
  geographicFocus: "Northern Ireland",
  dataPoints: [
    "Cost per m² for full restoration of listed Victorian house",
    "Elemental cost breakdown: roof, windows, masonry, plaster, joinery, services",
    "Specialist contractor uplift for listed buildings",
    "Planning/consent costs and timelines",
    "Named NI restoration projects with reported budgets",
    "Typical phasing strategy (Cat A urgent works → Cat B secondary → Cat C fit-out)",
    "Contingency norms for heritage projects (typically 20–30%)",
    "Fernhill-specific risks: scale, condition, access",
  ],
};

const placeholderData = {
  meta: {
    agent: "restoration-agent",
    version: "1.0.0",
    generated: new Date().toISOString(),
    status: "scaffold — populate via AI research run",
  },
  benchmarks: {
    costPerM2Full: "TODO: £2,500–£4,500/m² for full listed building restoration (NI, 2023–24)",
    costPerM2Refurb: "TODO: £1,200–£2,000/m² for partial refurbishment",
    listedBuildingUplift: "TODO: typically +25–40% vs standard construction",
    contingencyNorm: "20–30% of construction cost for heritage projects",
  },
  elementalCosts: {
    roof: "TODO: £180–£350/m² for slate re-roofing with heritage materials",
    windows: "TODO: £800–£2,500 per sash window repair/replacement (heritage spec)",
    masonry: "TODO: £80–£150/m² repointing; £200–£400/m² stonework repair",
    plasterwork: "TODO: £60–£120/m² for lime plaster restoration",
    timberJoinery: "TODO: £150–£300/m² specialist timber repairs",
    mechanicalElectrical: "TODO: £200–£400/m² full M&E replacement",
    accessAndScaffolding: "TODO: significant uplift for multi-storey Victorian houses",
  },
  niCaseStudies: [
    {
      name: "Clifton House, Belfast",
      date: "TODO",
      budget: "TODO",
      funder: "TODO",
      notes: "18th century poorhouse. Major restoration by Clifton House Trust.",
      source: "TODO",
    },
    {
      name: "Duncairn Centre, Belfast",
      date: "TODO",
      budget: "TODO",
      funder: "TODO",
      notes: "Former Presbyterian church converted to arts/community hub.",
      source: "TODO",
    },
    {
      name: "Roe Valley Arts Centre, Limavady",
      date: "TODO",
      budget: "TODO",
      funder: "TODO",
      notes: "Historic building adapted for arts use.",
      source: "TODO",
    },
  ],
  fernhillEstimate: {
    assumedGIA: "TODO: estimate Fernhill House gross internal area (m²)",
    phaseA: {
      description: "Urgent stabilisation — roof, masonry, water ingress",
      estimatedCost: "TODO",
    },
    phaseB: {
      description: "Core restoration — windows, plaster, joinery, services",
      estimatedCost: "TODO",
    },
    phaseC: {
      description: "Fit-out and commercial enablement — kitchen, accessibility, AV",
      estimatedCost: "TODO",
    },
    totalEstimate: "TODO",
    contingency: "TODO",
    totalWithContingency: "TODO",
  },
  citations: [],
};

async function run() {
  console.log("[restoration-agent] Starting research run...");

  const jsonOutput = JSON.stringify(placeholderData, null, 2);
  const mdOutput = `# Heritage Restoration Cost Benchmarks — NI Research Report
*Generated by restoration-agent v1.0.0 | ${new Date().toISOString()}*
*Status: scaffold — live data not yet populated*

---

## Cost Benchmarks

| Metric | Benchmark |
|--------|-----------|
| Full restoration cost/m² | ${placeholderData.benchmarks.costPerM2Full} |
| Partial refurbishment cost/m² | ${placeholderData.benchmarks.costPerM2Refurb} |
| Listed building uplift | ${placeholderData.benchmarks.listedBuildingUplift} |
| Contingency norm | ${placeholderData.benchmarks.contingencyNorm} |

---

## Elemental Cost Breakdown

| Element | Benchmark Cost |
|---------|---------------|
| Roof (slate, heritage spec) | ${placeholderData.elementalCosts.roof} |
| Sash windows | ${placeholderData.elementalCosts.windows} |
| Masonry / repointing | ${placeholderData.elementalCosts.masonry} |
| Lime plasterwork | ${placeholderData.elementalCosts.plasterwork} |
| Specialist timber/joinery | ${placeholderData.elementalCosts.timberJoinery} |
| M&E (mechanical & electrical) | ${placeholderData.elementalCosts.mechanicalElectrical} |
| Access & scaffolding | ${placeholderData.elementalCosts.accessAndScaffolding} |

---

## NI Case Studies

${placeholderData.niCaseStudies
  .map(
    (c) => `### ${c.name}
- **Date:** ${c.date}
- **Budget:** ${c.budget}
- **Funder:** ${c.funder}
- **Notes:** ${c.notes}
- **Source:** ${c.source}
`
  )
  .join("\n")}

---

## Fernhill-Specific Cost Estimate

| Phase | Description | Estimated Cost |
|-------|-------------|----------------|
| Phase A | ${placeholderData.fernhillEstimate.phaseA.description} | ${placeholderData.fernhillEstimate.phaseA.estimatedCost} |
| Phase B | ${placeholderData.fernhillEstimate.phaseB.description} | ${placeholderData.fernhillEstimate.phaseB.estimatedCost} |
| Phase C | ${placeholderData.fernhillEstimate.phaseC.description} | ${placeholderData.fernhillEstimate.phaseC.estimatedCost} |
| **Total** | | **${placeholderData.fernhillEstimate.totalEstimate}** |
| Contingency | | ${placeholderData.fernhillEstimate.contingency} |
| **Total inc. contingency** | | **${placeholderData.fernhillEstimate.totalWithContingency}** |

---

## Citations

*TODO: Add numbered citations with URLs.*

---
*This report is a scaffold. Run the agent with live AI research enabled to populate all TODO fields.*
`;

  await fs.mkdir(OUTPUT_DIR, { recursive: true });
  await fs.writeFile(path.join(OUTPUT_DIR, "restoration.json"), jsonOutput, "utf8");
  await fs.writeFile(path.join(OUTPUT_DIR, "restoration.md"), mdOutput, "utf8");

  console.log("[restoration-agent] Outputs written to", OUTPUT_DIR);
  return placeholderData;
}

export { run, RESEARCH_SCOPE };
