/**
 * WAKE & FUNERAL RECEPTION RESEARCH AGENT
 * ----------------------------------------
 * Researches the Belfast wake and funeral reception venue market.
 *
 * Outputs:
 *   research-output/wakes/wakes.json
 *   research-output/wakes/wakes.md
 *
 * Data targets:
 *   - Named Belfast wake/funeral reception venues
 *   - Capacities, catering options, pricing
 *   - Crematorium and funeral director proximity
 *   - Cultural expectations for Belfast wakes
 *   - Competitive positioning for Fernhill
 */

import fs from "fs/promises";
import path from "path";

const OUTPUT_DIR = "research-output/wakes";

const RESEARCH_SCOPE = {
  topic: "Belfast Wake & Funeral Reception Venue Market",
  geographicFocus: "Belfast, Northern Ireland",
  dataPoints: [
    "Named wake/funeral reception venues",
    "Capacity (standing and seated)",
    "Catering options (finger food, full meals, teas)",
    "Proximity to Belfast City Cemetery, Roselawn Crematorium, Dundonald Cemetery",
    "Price per head or room-hire rates",
    "Cultural sensitivities — Catholic/Protestant traditions in Belfast",
    "Growing demand for secular, celebrant-led remembrance",
    "Competitive gap for Fernhill (dignified, garden-setting)",
  ],
  keyVenues: [
    "The Stormont Hotel (funeral receptions)",
    "La Mon Hotel",
    "Malone Lodge Hotel",
    "The Balmoral Hotel",
    "Club venues and social clubs",
    "Church halls",
    "Dedicated funeral homes with reception rooms",
  ],
  crematoria: [
    { name: "Roselawn Crematorium", location: "Ballygowan Road, east Belfast" },
    { name: "Belfast City Cemetery", location: "Falls Road, west Belfast" },
    { name: "Dundonald Cemetery", location: "Dundonald, east Belfast" },
  ],
};

const placeholderData = {
  meta: {
    agent: "wake-agent",
    version: "1.0.0",
    generated: new Date().toISOString(),
    status: "scaffold — populate via AI research run",
  },
  marketOverview: {
    annualDeathsBelfast: "TODO: ~5,000–6,000 per year (NI Statistics)",
    receptionVenueUptake: "TODO: estimated % that book external venue",
    averageSpendPerReception: "TODO: ~£500–£2,000 catering spend",
    culturalNote:
      "Belfast wakes are traditionally home-based but venue receptions are growing post-COVID",
  },
  venues: [
    {
      name: "The Stormont Hotel",
      type: "hotel",
      capacity: { standing: 200, seated: 120 },
      catering: "Full menu available",
      proximityToRoselawn: "~15 min",
      pricePerHead: "TODO",
      notes: "Common choice for east Belfast and Stormont-area families",
      source: "TODO",
    },
    {
      name: "Malone Lodge Hotel",
      type: "hotel",
      capacity: { standing: 150, seated: 80 },
      catering: "Full menu available",
      proximityToRoselawn: "~25 min",
      pricePerHead: "TODO",
      notes: "South Belfast. Close to Fernhill's proposed location.",
      source: "TODO",
    },
  ],
  fernhillPositioning: {
    proposedOffer: "Dignified garden-house remembrance venue",
    uniqueFeatures: [
      "Peaceful walled garden for quiet reflection",
      "Intimate rooms — no hotel-banquet feel",
      "Community-rooted — resonant for local families",
      "South/west Belfast location — close to key crematoria and cemeteries",
      "Optional remembrance garden plot dedication",
    ],
    gap: "TODO: quantify underserved demand for dignified non-hotel wake venues in south/west Belfast",
  },
  citations: [],
};

async function run() {
  console.log("[wake-agent] Starting research run...");

  const jsonOutput = JSON.stringify(placeholderData, null, 2);
  const mdOutput = `# Belfast Wake & Funeral Reception Venue Market — Research Report
*Generated by wake-agent v1.0.0 | ${new Date().toISOString()}*
*Status: scaffold — live data not yet populated*

---

## Market Overview

- **Annual deaths in Belfast:** ${placeholderData.marketOverview.annualDeathsBelfast}
- **Venue uptake rate:** ${placeholderData.marketOverview.receptionVenueUptake}
- **Average reception spend:** ${placeholderData.marketOverview.averageSpendPerReception}
- **Cultural note:** ${placeholderData.marketOverview.culturalNote}

---

## Crematoria & Cemetery Proximity

| Name | Location |
|------|----------|
${RESEARCH_SCOPE.crematoria.map((c) => `| ${c.name} | ${c.location} |`).join("\n")}

---

## Named Wake Reception Venues

| Venue | Type | Standing | Seated | Price/Head |
|-------|------|----------|--------|------------|
${placeholderData.venues
  .map(
    (v) =>
      `| ${v.name} | ${v.type} | ${v.capacity.standing} | ${v.capacity.seated} | ${v.pricePerHead} |`
  )
  .join("\n")}

---

## Fernhill Positioning

**Proposed offer:** ${placeholderData.fernhillPositioning.proposedOffer}

**Unique features:**
${placeholderData.fernhillPositioning.uniqueFeatures.map((f) => `- ${f}`).join("\n")}

---

## Citations

*TODO: Add numbered citations with URLs.*

---
*This report is a scaffold. Run the agent with live AI research enabled to populate all TODO fields.*
`;

  await fs.mkdir(OUTPUT_DIR, { recursive: true });
  await fs.writeFile(path.join(OUTPUT_DIR, "wakes.json"), jsonOutput, "utf8");
  await fs.writeFile(path.join(OUTPUT_DIR, "wakes.md"), mdOutput, "utf8");

  console.log("[wake-agent] Outputs written to", OUTPUT_DIR);
  return placeholderData;
}

export { run, RESEARCH_SCOPE };
