/**
 * WEDDING RESEARCH AGENT
 * ----------------------
 * Researches the Belfast wedding venue market for the Fernhill Master Plan.
 *
 * Outputs:
 *   research-output/weddings/weddings.json   — structured data summary
 *   research-output/weddings/weddings.md     — full narrative report with citations
 *
 * Data targets:
 *   - Named Belfast wedding venues with capacity, pricing, min-spend
 *   - Heritage vs hotel vs restaurant split
 *   - Annual NI wedding volume & spend
 *   - Trends in NI wedding spending
 *   - Competitive positioning analysis for Fernhill
 */

import fs from "fs/promises";
import path from "path";

const OUTPUT_DIR = "research-output/weddings";

// ---------------------------------------------------------------------------
// RESEARCH SCOPE
// ---------------------------------------------------------------------------

const RESEARCH_SCOPE = {
  topic: "Belfast Wedding Venue Market",
  geographicFocus: "Belfast, Northern Ireland",
  dataPoints: [
    "Named venues with capacity, price-per-head, minimum spend",
    "Heritage venues specifically (houses, estates, castles)",
    "Hotel ballrooms and boutique hotels",
    "Restaurants and unconventional spaces",
    "Annual number of weddings in NI",
    "Average NI wedding spend (total and venue component)",
    "Trends: micro-weddings, heritage aesthetics, outdoor ceremonies",
    "Competitive gap analysis — where Fernhill could position",
  ],
  keyVenues: [
    "Belfast Castle",
    "Malone House",
    "The Merchant Hotel",
    "Titanic Belfast",
    "Galgorm Resort",
    "Killeavy Castle Estate",
    "Larchfield Estate",
    "The Balmoral Hotel",
    "Culloden Estate & Spa",
    "Hillsborough Castle",
  ],
};

// ---------------------------------------------------------------------------
// PLACEHOLDER DATA — replace with live AI/web-search results on execution
// ---------------------------------------------------------------------------

const placeholderData = {
  meta: {
    agent: "wedding-agent",
    version: "1.0.0",
    generated: new Date().toISOString(),
    status: "scaffold — populate via AI research run",
  },
  marketOverview: {
    annualWeddingsNI: "TODO: NISRA annual figure ~8,000–9,000",
    averageTotalSpend: "TODO: ~£25,000–£30,000 per wedding",
    venueShareOfSpend: "TODO: ~30–35% of total budget",
    heritageSegmentShare: "TODO: estimated 15–20% of venue bookings",
  },
  venues: [
    {
      name: "Belfast Castle",
      type: "heritage",
      capacity: { ceremony: 100, reception: 200 },
      pricePerHead: "TODO",
      minimumSpend: "TODO",
      notes: "Owned by Belfast City Council. Cave Hill backdrop.",
      source: "TODO",
    },
    {
      name: "Malone House",
      type: "heritage",
      capacity: { ceremony: 80, reception: 150 },
      pricePerHead: "TODO",
      minimumSpend: "TODO",
      notes: "Barnett Demesne. BCC managed.",
      source: "TODO",
    },
    {
      name: "The Merchant Hotel",
      type: "hotel",
      capacity: { ceremony: 120, reception: 280 },
      pricePerHead: "TODO",
      minimumSpend: "TODO",
      notes: "Victorian banking hall. Premium tier.",
      source: "TODO",
    },
  ],
  fernhillPositioning: {
    proposedTier: "mid-heritage — accessible luxury",
    differentiators: [
      "Community-rooted heritage narrative",
      "South Belfast location — underserved for heritage venues",
      "Gardens and grounds for outdoor ceremonies",
      "Intimate scale — 60–120 guests",
    ],
    gap: "TODO: quantify gap in south Belfast heritage wedding supply",
  },
  citations: [],
};

// ---------------------------------------------------------------------------
// AGENT RUN
// ---------------------------------------------------------------------------

async function run() {
  console.log("[wedding-agent] Starting research run...");

  // TODO: Replace this block with live AI/web-search calls.
  // Suggested approach:
  //   1. Use an LLM (OpenAI, Anthropic) with web-search tool enabled.
  //   2. Pass the prompt from /prompts/wedding-research.md.
  //   3. Parse structured output into the schema above.
  //   4. Append citations to placeholderData.citations[].

  const jsonOutput = JSON.stringify(placeholderData, null, 2);

  const mdOutput = `# Belfast Wedding Venue Market — Research Report
*Generated by wedding-agent v1.0.0 | ${new Date().toISOString()}*
*Status: scaffold — live data not yet populated*

---

## Market Overview

- **Annual weddings in NI:** ${placeholderData.marketOverview.annualWeddingsNI}
- **Average total wedding spend:** ${placeholderData.marketOverview.averageTotalSpend}
- **Venue share of spend:** ${placeholderData.marketOverview.venueShareOfSpend}
- **Heritage segment share:** ${placeholderData.marketOverview.heritageSegmentShare}

---

## Named Belfast Wedding Venues

| Venue | Type | Ceremony Cap. | Reception Cap. | Price/Head | Min. Spend |
|-------|------|--------------|----------------|------------|------------|
${placeholderData.venues
  .map(
    (v) =>
      `| ${v.name} | ${v.type} | ${v.capacity.ceremony} | ${v.capacity.reception} | ${v.pricePerHead} | ${v.minimumSpend} |`
  )
  .join("\n")}

*TODO: Expand to full venue list across all segments.*

---

## Fernhill Competitive Positioning

**Proposed tier:** ${placeholderData.fernhillPositioning.proposedTier}

**Key differentiators:**
${placeholderData.fernhillPositioning.differentiators.map((d) => `- ${d}`).join("\n")}

**Market gap:** ${placeholderData.fernhillPositioning.gap}

---

## Citations

*TODO: Add numbered citations with URLs for all factual claims.*

---
*This report is a scaffold. Run the agent with live AI research enabled to populate all TODO fields.*
`;

  await fs.mkdir(OUTPUT_DIR, { recursive: true });
  await fs.writeFile(path.join(OUTPUT_DIR, "weddings.json"), jsonOutput, "utf8");
  await fs.writeFile(path.join(OUTPUT_DIR, "weddings.md"), mdOutput, "utf8");

  console.log("[wedding-agent] Outputs written to", OUTPUT_DIR);
  return placeholderData;
}

export { run, RESEARCH_SCOPE };
